language: python
os: linux
sudo: required
dist: xenial

python:
    - 3.6
notifications:
    email: false


before_install:
    - pip install black
    - pip install future
    - pip install pytest
    - pip install pydocstyle

install:
    - pip install .

script:
    # Run black on all .py files in all subfolders
    - black --check .
    - pydocstyle --convention=numpy .
