language: python
os: linux
sudo: required
dist: xenial

python:
    - 3.6

notifications:
    email: false

services:
    - mysql

before_install:
    - pip install black
    - pip install future
    - pip install pytest
    - pip install pydocstyle

install:
    - pip install .

before_script:
    - mysql -e "CREATE DATABASE test;"

script:
    # Run black on all .py files in all subfolders
    - black --check .

    # check docstrings
    - find . ! -name versioneer.py ! -name test_*.py ! -name _version.py -name \*.py -exec pydocstyle --convention=numpy --add-ignore=D105 {} +

    # unit tests
    - export PYTHONPATH=.:$PYTHONPATH
    - cd tests
    - pytest -x
