name: chimedb_dataset-ci-build
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:

  lint-code:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install black
      run: pip install black ruff

    - name: Check code with black
      run: |
        black --check .

    - name: Run ruff
      run: ruff check .

  run-tests:

    strategy:
      matrix:
        python-version: ["3.10", "3.13"]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip dependencies
      run: |
        pip install pytest

    - name: Install chimedb_dataset
      run: |
        pip install .

    - name: Run tests
      # Set PYTHONPATH so that relative imports in click script work when pytest imports that
      run: |
        touch $CHIMEDB_TEST_SQLITE
        pytest -sv tests/
      env:
        CHIMEDB_TEST_ENABLE: 1
        CHIMEDB_TEST_SQLITE: test.sql
