name: chimedb_dataset-ci-build
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:

  lint-code:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"

    - name: Install black
      run: pip install black flake8

    - name: Check code with black
      run: |
        black --check .

    - name: Run flake8
      # ignore: line too long, variable names, whitespace before ':', line break before
      # binary operator, comment style
      run: flake8 --show-source --ignore=E501,E741,E203,W503,E266 chimedb

  run-tests:

    strategy:
      matrix:
        python-version: ["3.8", "3.12"]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip dependencies
      run: |
        pip install pytest

    - name: Install chimedb_dataset
      run: |
        pip install .

    - name: Run tests
      # Set PYTHONPATH so that relative imports in click script work when pytest imports that
      run: |
        touch $CHIMEDB_TEST_SQLITE
        pytest -sv tests/
      env:
        CHIMEDB_TEST_ENABLE: 1
        CHIMEDB_TEST_SQLITE: test.sql
